### ISSUE TITLE
Review ES6 tooling options

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/generator-es6#1]
From https://github.com/addyosmani/es6-tools.

We use ES6 module transpiler by default.

Currently thinking of using https://github.com/thomasboyt/grunt-microlib 

with a Gruntfile like https://github.com/jakearchibald/ES6-Promises/blob/c3336087fffc52e66cf5398e5b56b23a291080fc/Gruntfile.js.

**Comment by addyosmani** [comment]
Potential default experience:
- ES6 module transpiler etc via grunt-microlib
- Options for index.html, Bootstrap (CSS only)?

**Comment by sindresorhus** [comment]
Why only modules? Since this generator is called generator-es6 shouldn't it support the rest of the ES6 features, with eg Traceur.

**Comment by addyosmani** [comment]
GH was down last night but my local version supports ES6 transpiler too. I
was considering using it vs. Traceur for now but interested in your opinion.

I want to create something which can practically be used for small
production apps.

**Comment by addyosmani** [comment]
Experimental support for using ES6 module transpiler + Traceur at the same time landed. Need to clean up the setup so that the output of both actually get concat/combined into something sane, but it's working.
